### ISSUE TITLE
Unity3d 5.5.03f: undefined variable oneMinusRoughness d3d9 LuxStandardBRDF.cginc:95

### ISSUE THREAD

**Issue by HWiese1980** [larsbertram69/Lux-2.01#2]
Hi,

I've got an issue with many of the included shaders that are based of LuxStandardBRDF.cginc. The compiler keeps giving me the error message 

    undefined variable "oneMinusRoughness" in LuxStandardBRDF.cginc:95

Could you take a look into this? That'd be great!

Cheers and a happy (quite) new year!

**Comment by HWiese1980** [comment]
Just realized that the error is already fixed in the current github state. Not so however in the asset store as it seems... or is it?

**Comment by larsbertram69** [comment]
> 



hi hendrik,

something went terribly wrong with the latest update…
sorry about that.

but you could grab the version from github which should be fine:
https://github.com/larsbertram69/Lux-2.01 <https://github.com/larsbertram69/Lux-2.01>

happy new year,

lars

**Comment by dkyeck** [comment]
> Just realized that the error is already fixed in the current github state. Not so however in the asset store as it seems... or has it?
> 

did not see this email when i wrote the answer...

**Comment by larsbertram69** [comment]
hi hendrif,

i just checked the asset store version which is from decembeer 20th – just like the github version.
so i think both are the same.

are you sure you got the latest version from the asset store?

lars

**Comment by HWiese1980** [comment]
Hey Lars,

it must have been updated within the last two weeks. I think I downloaded it the last time about two or three weeks ago... so, yes, the current Asset Store version seems to be working fine as well. Thus, I'll close the issue. Thanks and keep up the great work!

**Comment by dkyeck** [comment]
> Hey Lars,
> 
> it must have been updated within the last two weeks. I think I downloaded it the last time about two or three weeks ago... so, yes, the current Asset Store version seems to be working fine as well. Thus, I'll close the issue. Thanks and keep up the great work!
> 

great!

**Comment by HWiese1980** [comment]
There needs to be some kind of auto-update feature for assets from the asset store...
